# Generated by Django 3.2.20 on 2023-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_posts_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
