# Generated by Django 3.2.20 on 2023-08-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
