# Generated by Django 3.2.20 on 2023-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_posts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
