# Generated by Django 3.2.20 on 2023-08-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20230901_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image_width',
        ),
    ]
