# Generated by Django 3.2.20 on 2023-08-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20230901_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='tree_DePLgRY.jpg', upload_to='media'),
        ),
    ]
