# Generated by Django 3.2.20 on 2023-09-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_custommanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomManager',
        ),
    ]
