# Generated by Django 3.2.21 on 2023-10-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_auto_20231010_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Post Picture', upload_to=''),
        ),
    ]
